import { notFound } from "next/navigation";
import Link from "next/link";
import { activities, cases, caseTasks, customers, users } from "@/data/sample-data";
import { Badge, ProgressBar } from "@/components/ui";
import { calculateCaseProgress } from "@/lib/case-progress";
import { customerFor, fullName, tasksForCase, userFor } from "@/lib/case-selectors";
import { formatDate } from "@/lib/format";
export function generateStaticParams(){return cases.map(item=>({caseId:item.id}))}
export default async function Page({params}:{params:Promise<{caseId:string}>}){const {caseId}=await params;const item=cases.find(c=>c.id===caseId);if(!item)notFound();const tasks=tasksForCase(item.id,caseTasks);const progress=calculateCaseProgress(tasks);const caseActivities=activities.filter(a=>a.caseId===item.id).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));return <>
 <div className="detail-header"><div className="breadcrumb"><Link href="/cases">Cases</Link><span>/</span>{item.caseNumber}</div><div className="detail-title"><div><span className="eyebrow">{item.caseNumber}</span><h1>{item.title}</h1><p>{customerFor(item,customers)?.name} · {item.caseType}</p></div><div className="detail-badges"><Badge value={item.status}/><Badge value={item.priority}/></div></div><div className="detail-progress"><div><span>Overall progress</span><b>{progress.completedRequiredTasks} of {progress.totalRequiredTasks} required tasks complete</b></div><ProgressBar percentage={progress.percentage}/><div><span>Due date</span><b>{formatDate(item.dueAt)}</b></div></div></div>
 <div className="detail-grid"><div className="detail-main"><section className="panel detail-section"><div className="section-head"><div><h2>Case Overview</h2><p>Core case information and ownership</p></div></div><p className="description">{item.description}</p><dl className="overview-grid"><div><dt>Case type</dt><dd>{item.caseType}</dd></div><div><dt>Opened</dt><dd>{formatDate(item.openedAt)}</dd></div><div><dt>Manager</dt><dd>{fullName(userFor(item.managerUserId,users))}</dd></div><div><dt>Last updated</dt><dd>{formatDate(item.updatedAt)}</dd></div></dl></section>
 <section className="panel detail-section"><div className="section-head"><div><h2>Tasks</h2><p>Required work determines overall case progress</p></div><span className="count-pill">{progress.remainingRequiredTasks} remaining</span></div><div className="task-list">{tasks.map(task=><article key={task.id}><span className={`task-check ${task.status==="COMPLETED"?"done":""}`}>{task.status==="COMPLETED"?"✓":task.sequence}</span><div><b>{task.title}</b><span>{fullName(userFor(task.assignedUserId,users))} · Due {formatDate(task.dueAt)}</span></div><span className={task.required?"required":"optional"}>{task.required?"Required":"Optional"}</span><Badge value={task.status}/></article>)}</div><div className="progress-explainer"><b>{progress.percentage}% complete</b><span>Completed required tasks ({progress.completedRequiredTasks}) ÷ applicable required tasks ({progress.totalRequiredTasks})</span></div></section>
 <section className="panel detail-section"><div className="section-head"><div><h2>Activity</h2><p>Chronological case event history</p></div></div><div className="timeline">{caseActivities.length?caseActivities.map(a=><article key={a.id}><span/><div><b>{a.summary}</b><p>{fullName(userFor(a.actorUserId,users))} · {formatDate(a.occurredAt)}</p></div></article>):<p>No activity recorded yet.</p>}</div></section></div>
 <aside className="detail-side"><section className="panel detail-section"><h2>Assigned Staff</h2>{item.assignedUserIds.length?<div className="assigned-list">{item.assignedUserIds.map(id=>{const u=userFor(id,users);return <div key={id}><span className="avatar">{u?.firstName[0]}{u?.lastName[0]}</span><span><b>{fullName(u)}</b><small>{u?.title}</small></span></div>})}</div>:<p className="muted">This case is not assigned.</p>}</section>{[["Requirements / Questions","Configurable requirements and customer responses will appear here."],["Customer Communications","Linked conversations and correspondence will appear here."],["Attachments","Case documents and evidence will appear here."],["Completion Review","Completion rules and final approval will appear here."]].map(([title,text])=><section className="panel future-panel" key={title}><span>◇</span><div><h3>{title}</h3><p>{text}</p><small>Future milestone</small></div></section>)}</aside></div></>}
