import Link from "next/link";
import { activities, cases, caseTasks, users } from "@/data/sample-data";
import { getDashboardMetrics } from "@/lib/dashboard-metrics";
import { fullName, isActiveCase, isCaseOverdue, userFor } from "@/lib/case-selectors";
import { formatRelativeDate } from "@/lib/format";
import { CaseTable } from "@/components/cases/case-table";
const NOW=new Date("2026-09-03T15:00:00Z");
export function Dashboard(){const metrics=getDashboardMetrics(cases,NOW);const workload=users.filter(u=>u.role==="STAFF_USER").map(user=>{const assignedCases=cases.filter(c=>c.assignedUserIds.includes(user.id)&&isActiveCase(c));const tasks=caseTasks.filter(t=>t.assignedUserId===user.id);return {user,active:assignedCases.length,assigned:tasks.filter(t=>t.status!=="COMPLETED"&&t.status!=="NOT_APPLICABLE").length,completed:tasks.filter(t=>t.status==="COMPLETED").length,overdue:tasks.filter(t=>t.dueAt&&new Date(t.dueAt)<NOW&&t.status!=="COMPLETED"&&t.status!=="NOT_APPLICABLE").length};});return <>
 <div className="metric-grid">{metrics.map((m,i)=><article className={`metric tone-${m.tone}`} key={m.label}><div><span>{m.label}</span><strong>{m.value}</strong></div><span className="metric-icon">{["▤","◴","✓","○","!","◇","Ⅱ","⌁"][i]}</span><small>{m.label==="Overdue"?"Needs attention":m.label==="Due Soon"?"Next 7 days":"Current caseload"}</small></article>)}</div>
 <section className="panel"><div className="section-head"><div><h2>Case Workload</h2><p>Active and recently updated operational cases</p></div><Link href="/cases">View all cases <span>→</span></Link></div><CaseTable items={cases.filter(c=>isActiveCase(c)).slice(0,6)} compact/></section>
 <div className="dashboard-lower"><section className="panel"><div className="section-head"><div><h2>Staff Workload</h2><p>Assignments and task volume by team member</p></div><Link href="/tasks">View tasks →</Link></div><div className="workload-list"><div className="workload-row heading"><span>Staff Member</span><span>Active Cases</span><span>Assigned Tasks</span><span>Completed</span><span>Overdue</span></div>{workload.map(({user,...x})=><div className="workload-row" key={user.id}><span className="staff-cell"><span className="avatar small">{user.firstName[0]}{user.lastName[0]}</span><span><b>{fullName(user)}</b><small>{user.title}</small></span></span><b>{x.active}</b><b>{x.assigned}</b><b className="success-text">{x.completed}</b><b className={x.overdue?"danger-text":""}>{x.overdue}</b></div>)}</div></section>
 <section className="panel"><div className="section-head"><div><h2>Recent Activity</h2><p>Latest updates across the workspace</p></div></div><div className="activity-list">{activities.slice(0,5).map(a=>{const item=cases.find(c=>c.id===a.caseId);return <article key={a.id}><span className={`activity-dot ${a.type.toLowerCase()}`}>{a.type==="TASK_COMPLETED"||a.type==="CASE_COMPLETED"?"✓":a.type==="CUSTOMER_RESPONSE"?"↙":"•"}</span><div><p>{a.summary}</p><span>{item?.caseNumber} · {fullName(userFor(a.actorUserId,users))}</span></div><time>{formatRelativeDate(a.occurredAt,NOW)}</time></article>})}</div></section></div>
 <div className="attention"><strong>{cases.filter(c=>isCaseOverdue(c,NOW)).length} overdue cases require attention</strong><Link href="/cases">Review case register →</Link></div>
 </>}
