"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { BarChart3, BriefcaseBusiness, ClipboardCheck, FileQuestion, Headphones, LayoutDashboard, LogOut, Menu, Settings, ShieldCheck, Users, X } from "lucide-react";
import { signOutAction } from "@/lib/auth/actions";
const nav=[{href:"/",label:"Dashboard",icon:LayoutDashboard},{href:"/cases",label:"Cases",icon:BriefcaseBusiness},{href:"/service-desk",label:"Service Desk",icon:Headphones},{href:"/customers",label:"Customers",icon:Users},{href:"/tasks",label:"Tasks",icon:ClipboardCheck},{href:"/questions",label:"Questions & Rules",icon:FileQuestion},{href:"/reports",label:"Reports",icon:BarChart3},{href:"/users",label:"Users",icon:Users},{href:"/administration",label:"Administration",icon:ShieldCheck},{href:"/settings",label:"Settings",icon:Settings}];
const isPublic=(path:string)=>path==="/login"||path.startsWith("/auth/")||path==="/account/unprovisioned";
export function AppShell({children}:{children:React.ReactNode}){const pathname=usePathname();const [open,setOpen]=useState(false);if(isPublic(pathname))return <main className="public-main">{children}</main>;return <div className="app-frame">{open&&<button className="scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`sidebar ${open?"open":""}`}><div className="brand-row"><Link href="/" className="brand"><strong>DM3iQ™</strong><span>Case Management Intelligence</span></Link><button className="close-menu" aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button></div><nav aria-label="Primary navigation">{nav.map(({href,label,icon:Icon})=>{const active=href==="/"?pathname===href:pathname.startsWith(href);return <Link key={href} href={href} onClick={()=>setOpen(false)} className={active?"active":""}><Icon aria-hidden/><span>{label}</span></Link>})}</nav><div className="organization-card"><span>Organization</span><div><span className="avatar">NC</span><p><strong>Northstar Community Services</strong><small>Business Administrator</small></p></div></div><form action={signOutAction} className="signout"><button type="submit"><LogOut/>Sign Out</button></form></aside><div className="main-column"><header className="topbar"><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu/></button><div className="workspace"><strong>Case Management Intelligence</strong><small>Northstar Community Services</small></div><span className="avatar">MC</span></header><main>{children}</main></div></div>}
