"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { updateCustomerAction } from "@/lib/data/customer-actions";
import { normalizeCustomerPhone } from "@/lib/customer-validation";
type Values={name:string;email:string;phone:string;notes:string;status:string};
const canonical=(values:Values)=>({name:values.name.trim(),email:values.email.trim().toLowerCase(),phone:normalizeCustomerPhone(values.phone)??values.phone.trim(),notes:values.notes.trim(),status:values.status});
export function CustomerEditForm({customerId,initial}:{customerId:string;initial:Values}){const router=useRouter();const [values,setValues]=useState(initial);const [saved,setSaved]=useState(initial);const [errors,setErrors]=useState<Record<string,string>>({});const [summary,setSummary]=useState<string|null>(null);const [pending,setPending]=useState(false);const [justSaved,setJustSaved]=useState(false);const dirty=JSON.stringify(canonical(values))!==JSON.stringify(canonical(saved));const update=(key:keyof Values,value:string)=>{setValues(v=>({...v,[key]:value}));setErrors(e=>({...e,[key]:""}));setSummary(null);setJustSaved(false)};const field=(key:keyof Values,label:string,type="text")=><label><span>{label}</span><input name={key} type={type} required value={values[key]} onChange={e=>update(key,e.target.value)} aria-invalid={Boolean(errors[key])} aria-describedby={errors[key]?`${key}-error`:undefined}/>{errors[key]?<small id={`${key}-error`} className="field-error" role="alert">{errors[key]}</small>:null}</label>;return <form onSubmit={async event=>{event.preventDefault();setPending(true);setSummary(null);const result=await updateCustomerAction(new FormData(event.currentTarget));setPending(false);if(!result.ok){setValues(result.values);setErrors(result.fieldErrors);setSummary(result.error);return;}setSaved(values);setJustSaved(true);router.refresh();}} className="entity-form"><input type="hidden" name="customerId" value={customerId}/><div className="form-grid">{field("name","Name")} {field("email","Email","email")} {field("phone","Phone","tel")}<label><span>Status</span><select name="status" value={values.status} onChange={e=>update("status",e.target.value)} aria-invalid={Boolean(errors.status)} aria-describedby={errors.status?"status-error":undefined}><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="ARCHIVED">Archived</option></select>{errors.status?<small id="status-error" className="field-error" role="alert">{errors.status}</small>:null}</label><label className="full"><span>Notes <small>Optional</small></span><textarea name="notes" rows={5} value={values.notes} onChange={e=>update("notes",e.target.value)}/></label></div>{summary?<div className="form-alert" role="alert">{summary}</div>:null}<div className="form-actions"><Link href={`/customers/${customerId}`}>Cancel</Link><button className={dirty?"license-save-button":"primary-button"} type="submit" disabled={pending}>{pending?"Saving…":justSaved?"Changes Saved":"Save changes"}</button></div></form>}
