"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState } from "react";
import { saveLicenseAction } from "@/lib/data/license-actions";
export function LicenseForm({ organizationId, license }: { organizationId:string; license:any }) {
  const initial={status:license?.license_status??"TRIAL",commercialState:license?.commercial_state??"TRIAL",planCode:license?.plan_code??"STANDARD",startsAt:license?.starts_at?.slice(0,16)??"",expiresAt:license?.expires_at?.slice(0,16)??"",graceEndsAt:license?.grace_ends_at?.slice(0,16)??"",notes:license?.notes??""};
  const [values,setValues]=useState(initial); const [saved,setSaved]=useState(initial); const [pending,setPending]=useState(false); const [error,setError]=useState<string|null>(null); const [justSaved,setJustSaved]=useState(false); const dirty=JSON.stringify(values)!==JSON.stringify(saved);
  const update=(key:string,value:string)=>{setValues(v=>({...v,[key]:value}));setError(null);setJustSaved(false);};
  return <form className="entity-form" onSubmit={async e=>{e.preventDefault();setPending(true);setError(null);const form=new FormData(e.currentTarget);const result=await saveLicenseAction(form);setPending(false);if(!result.ok){setError(result.error??"License could not be saved.");return;}setSaved(values);setJustSaved(true);}}><input type="hidden" name="organizationId" value={organizationId}/><div className="form-grid"><label><span>License status</span><select name="status" value={values.status} onChange={e=>update("status",e.target.value)}>{["TRIAL","ACTIVE","EXPIRING","EXPIRED","SUSPENDED","CANCELLED"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Commercial state</span><select name="commercialState" value={values.commercialState} onChange={e=>update("commercialState",e.target.value)}>{["TRIAL","PAID","UNPAID","COMP","INTERNAL"].map(v=><option key={v}>{v}</option>)}</select></label><label><span>Plan</span><input name="planCode" value={values.planCode} onChange={e=>update("planCode",e.target.value)}/></label><label><span>Start date</span><input type="datetime-local" name="startsAt" value={values.startsAt} onChange={e=>update("startsAt",e.target.value)}/></label><label><span>Expiration date</span><input type="datetime-local" name="expiresAt" value={values.expiresAt} onChange={e=>update("expiresAt",e.target.value)}/></label><label><span>Grace end date</span><input type="datetime-local" name="graceEndsAt" value={values.graceEndsAt} onChange={e=>update("graceEndsAt",e.target.value)}/></label><label className="full"><span>Notes</span><textarea name="notes" value={values.notes} onChange={e=>update("notes",e.target.value)}/></label></div>{error?<p className="form-alert" role="alert">{error}</p>:null}<div className="form-actions"><button className={dirty?"license-save-button dirty":"primary-button"} disabled={pending} aria-disabled={pending}>{pending?"Saving…":justSaved?"License Saved":"Save License"}</button></div></form>;
}
