import type { LiveCase } from "@/lib/data/case-repository";
import type { LiveServiceRequest } from "@/lib/data/case-repository";
const terminal=new Set(["COMPLETED","CLOSED","CANCELLED"]);
export const isLiveCaseOverdue=(item:LiveCase,now=new Date())=>Boolean(item.due_at&&new Date(item.due_at)<now&&!terminal.has(item.status));
export const isLiveCaseDueSoon=(item:LiveCase,now=new Date())=>{if(!item.due_at||terminal.has(item.status))return false;const due=new Date(item.due_at);const end=new Date(now);end.setDate(end.getDate()+3);end.setHours(23,59,59,999);return due>=now&&due<=end;};
export const isLiveCaseActive=(item:LiveCase)=>!terminal.has(item.status);
export function getLiveDashboardMetrics(cases:LiveCase[],now=new Date()){return[{label:"Total Cases",value:cases.length,tone:"blue"},{label:"In Progress",value:cases.filter(c=>c.status==="IN_PROGRESS").length,tone:"cyan"},{label:"Completed",value:cases.filter(c=>c.status==="COMPLETED"||c.status==="CLOSED").length,tone:"green"},{label:"Unassigned",value:cases.filter(c=>c.status==="UNASSIGNED"||(!c.manager_user_id&&!c.assignedStaff.length)).length,tone:"amber"},{label:"Overdue",value:cases.filter(c=>isLiveCaseOverdue(c,now)).length,tone:"red"},{label:"In Review",value:cases.filter(c=>c.status==="REVIEW").length,tone:"violet"},{label:"Waiting",value:cases.filter(c=>c.status==="WAITING").length,tone:"slate"},{label:"Due Soon",value:cases.filter(c=>isLiveCaseDueSoon(c,now)).length,tone:"orange"}] as const;}
export const isLiveServiceRequestActive=(item:LiveServiceRequest)=>["NEW","OPEN","PENDING_CUSTOMER","PENDING_STAFF","ON_HOLD"].includes(item.status as string);
export function getServiceRequestMetrics(items:LiveServiceRequest[]){const active=items.filter(isLiveServiceRequestActive);return [{label:"Open",value:active.length,tone:"blue",href:"/service-desk/requests?status=open"},{label:"New",value:items.filter(item=>item.status==="NEW").length,tone:"cyan",href:"/service-desk/requests?status=NEW"},{label:"Waiting on Customer",value:items.filter(item=>item.status==="PENDING_CUSTOMER").length,tone:"amber",href:"/service-desk/requests?status=PENDING_CUSTOMER"},{label:"On Hold",value:items.filter(item=>(item.status as string)==="ON_HOLD").length,tone:"slate",href:"/service-desk/requests?status=ON_HOLD"},{label:"Unassigned",value:active.filter(item=>!item.assigned_user_id).length,tone:"orange",href:"/service-desk/requests?assignment=unassigned"},{label:"Urgent",value:active.filter(item=>item.priority==="URGENT").length,tone:"red",href:"/service-desk/requests?priority=URGENT"},{label:"Resolved",value:items.filter(item=>["RESOLVED","CLOSED"].includes(item.status)).length,tone:"green",href:"/service-desk/requests?status=resolved"},{label:"Total Requests",value:items.length,tone:"violet",href:"/service-desk/requests"}] as const;}
