import Link from "next/link";
import { AuthCard } from "@/components/auth-card";
import { sendLoginOtpAction, signInAction, verifyLoginOtpAction } from "@/lib/auth/actions";
import { isSupabaseConfigured } from "@/lib/supabase/server";
type Params={error?:string;message?:string;next?:string;mode?:string;sent?:string;email?:string};
export const metadata={title:"Sign in"};
export default async function LoginPage({searchParams}:{searchParams?:Promise<Params>}){const params=await searchParams;const mode=params?.mode==="otp"?"otp":"password";const sent=mode==="otp"&&params?.sent==="1";const email=params?.email??"";const next=params?.next??"";const error=!isSupabaseConfigured()?"Supabase environment variables are not configured.":params?.error;const href=(selected:string)=>`/login?${new URLSearchParams({mode:selected,...(email?{email}:{}),...(next?{next}:{})}).toString()}`;return <AuthCard title="Sign in" description="Access your DM3iQ Case Management Intelligence workspace." error={error}>
 {params?.message?<div className="auth-message">{params.message}</div>:null}<div className="auth-tabs"><Link className={mode==="password"?"active":""} href={href("password")}>Password</Link><Link className={mode==="otp"?"active":""} href={href("otp")}>Email Code</Link></div>
 {mode==="password"?<form action={signInAction} className="auth-form"><input type="hidden" name="next" value={next}/><label><span>Email</span><input name="email" type="email" required defaultValue={email} autoComplete="email"/></label><label><span>Password</span><input name="password" type="password" required autoComplete="current-password"/></label><button type="submit">Sign In</button></form>:sent?<form action={verifyLoginOtpAction} className="auth-form"><input type="hidden" name="email" value={email}/><input type="hidden" name="next" value={next}/><div className="auth-message">We sent a login code to <b>{email}</b>.</div><label><span>Email Code</span><input className="code-input" name="token" inputMode="numeric" autoComplete="one-time-code" required autoFocus placeholder="000000"/></label><button type="submit">Verify &amp; Sign In</button><Link className="auth-link" href={`/login?mode=otp&email=${encodeURIComponent(email)}${next?`&next=${encodeURIComponent(next)}`:""}`}>Send another code</Link></form>:<form action={sendLoginOtpAction} className="auth-form"><input type="hidden" name="next" value={next}/><label><span>Email</span><input name="email" type="email" required defaultValue={email} autoComplete="email"/></label><p>DM3iQ will email you a one-time login code. No password is required.</p><button type="submit">Send Code</button></form>}
 </AuthCard>}
