-- DM3iQCM-05: tenant question definitions, immutable case snapshots, and typed responses.
create type public.question_response_type as enum ('TEXT','LONG_TEXT','YES_NO','SINGLE_SELECT','MULTI_SELECT','DATE','NUMBER');

create table public.question_definitions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,question_text text not null check(length(trim(question_text))>0),description text not null default '',response_type public.question_response_type not null,required boolean not null default false,active boolean not null default true,display_order integer not null default 0 check(display_order>=0),created_by_user_id uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id));
create table public.question_options(id uuid primary key default gen_random_uuid(),organization_id uuid not null,question_id uuid not null,option_label text not null check(length(trim(option_label))>0),option_value text not null check(length(trim(option_value))>0),display_order integer not null default 0 check(display_order>=0),created_at timestamptz not null default now(),unique(question_id,option_value),foreign key(organization_id,question_id) references public.question_definitions(organization_id,id) on delete cascade);
create table public.case_questions(id uuid primary key default gen_random_uuid(),organization_id uuid not null,case_id uuid not null,question_definition_id uuid,question_text text not null,description text not null default '',response_type public.question_response_type not null,required boolean not null,display_order integer not null,options_snapshot jsonb not null default '[]' check(jsonb_typeof(options_snapshot)='array'),created_at timestamptz not null default now(),unique(case_id,question_definition_id),unique(organization_id,id),foreign key(organization_id,case_id) references public.cases(organization_id,id) on delete cascade,foreign key(organization_id,question_definition_id) references public.question_definitions(organization_id,id) on delete set null);
create table public.case_question_responses(id uuid primary key default gen_random_uuid(),organization_id uuid not null,case_id uuid not null,case_question_id uuid not null,response_value jsonb not null,responded_by_user_id uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(case_question_id),foreign key(organization_id,case_id) references public.cases(organization_id,id) on delete cascade,foreign key(organization_id,case_question_id) references public.case_questions(organization_id,id) on delete cascade);
create index question_definitions_order_idx on public.question_definitions(organization_id,active,display_order);create index case_questions_order_idx on public.case_questions(case_id,display_order);

create trigger question_definitions_updated_at before update on public.question_definitions for each row execute function public.set_updated_at();create trigger case_question_responses_updated_at before update on public.case_question_responses for each row execute function public.set_updated_at();
create trigger question_definitions_actor_integrity before insert or update of organization_id,created_by_user_id on public.question_definitions for each row execute function public.validate_organization_actor('created_by_user_id');create trigger responses_actor_integrity before insert or update of organization_id,responded_by_user_id on public.case_question_responses for each row execute function public.validate_organization_actor('responded_by_user_id');

create or replace function public.can_access_case(check_case_id uuid,check_organization_id uuid,check_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$ select public.is_super_admin(check_user_id) or (public.is_internal_member(check_organization_id,check_user_id) and (public.has_organization_role(check_organization_id,array['BUSINESS_ADMIN','BUSINESS_OWNER','STAFF_MANAGER']::public.application_role[],check_user_id) or exists(select 1 from public.case_assignments a where a.case_id=check_case_id and a.organization_id=check_organization_id and a.user_id=check_user_id and a.is_active) or exists(select 1 from public.case_tasks t where t.case_id=check_case_id and t.organization_id=check_organization_id and t.assigned_user_id=check_user_id))) $$;
create or replace function public.can_administer_questions(target_organization_id uuid,target_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$ select public.is_super_admin(target_user_id) or public.has_organization_role(target_organization_id,array['BUSINESS_ADMIN','BUSINESS_OWNER','STAFF_MANAGER']::public.application_role[],target_user_id) $$;

create or replace function public.snapshot_case_questions() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.case_questions(organization_id,case_id,question_definition_id,question_text,description,response_type,required,display_order,options_snapshot) select q.organization_id,new.id,q.id,q.question_text,q.description,q.response_type,q.required,q.display_order,coalesce((select jsonb_agg(jsonb_build_object('label',o.option_label,'value',o.option_value) order by o.display_order) from public.question_options o where o.question_id=q.id),'[]') from public.question_definitions q where q.organization_id=new.organization_id and q.active order by q.display_order;return new;end $$;
create trigger cases_snapshot_questions after insert on public.cases for each row execute function public.snapshot_case_questions();

create or replace function public.save_question_definition(target_organization_id uuid,target_question_id uuid,target_question_text text,target_description text,target_response_type public.question_response_type,target_required boolean,target_active boolean,target_display_order integer,target_options jsonb default '[]') returns public.question_definitions language plpgsql security definer set search_path='' as $$ declare actor uuid:=auth.uid();item public.question_definitions;opt jsonb;begin if not public.can_administer_questions(target_organization_id,actor) then raise exception 'not authorized' using errcode='42501';end if;if jsonb_typeof(target_options)<>'array' then raise exception 'options must be an array' using errcode='22023';end if;if target_response_type in ('SINGLE_SELECT','MULTI_SELECT') and jsonb_array_length(target_options)=0 then raise exception 'select questions require options' using errcode='23514';end if;if target_question_id is null then insert into public.question_definitions(organization_id,question_text,description,response_type,required,active,display_order,created_by_user_id) values(target_organization_id,trim(target_question_text),coalesce(target_description,''),target_response_type,target_required,target_active,target_display_order,actor) returning * into item;else update public.question_definitions set question_text=trim(target_question_text),description=coalesce(target_description,''),response_type=target_response_type,required=target_required,active=target_active,display_order=target_display_order where id=target_question_id and organization_id=target_organization_id returning * into item;if not found then raise exception 'question not found' using errcode='P0002';end if;delete from public.question_options where question_id=item.id;end if;for opt in select value from jsonb_array_elements(target_options) loop insert into public.question_options(organization_id,question_id,option_label,option_value,display_order) values(target_organization_id,item.id,trim(opt->>'label'),trim(opt->>'value'),coalesce((opt->>'display_order')::integer,0));end loop;return item;end $$;

create or replace function public.save_case_question_response(target_case_question_id uuid,target_response_value jsonb) returns public.case_question_responses language plpgsql security definer set search_path='' as $$ declare actor uuid:=auth.uid();q public.case_questions;r public.case_question_responses;valid boolean;begin select * into q from public.case_questions where id=target_case_question_id;if not found then raise exception 'case question not found' using errcode='P0002';end if;if not public.can_access_case(q.case_id,q.organization_id,actor) then raise exception 'not authorized' using errcode='42501';end if;valid:=case q.response_type when 'YES_NO' then jsonb_typeof(target_response_value)='boolean' when 'NUMBER' then jsonb_typeof(target_response_value)='number' when 'DATE' then jsonb_typeof(target_response_value)='string' and (target_response_value#>>'{}')~'^\d{4}-\d{2}-\d{2}$' when 'TEXT' then jsonb_typeof(target_response_value)='string' and length(trim(target_response_value#>>'{}'))>0 when 'LONG_TEXT' then jsonb_typeof(target_response_value)='string' and length(trim(target_response_value#>>'{}'))>0 when 'SINGLE_SELECT' then jsonb_typeof(target_response_value)='string' and exists(select 1 from jsonb_array_elements(q.options_snapshot) o where o->>'value'=target_response_value#>>'{}') when 'MULTI_SELECT' then jsonb_typeof(target_response_value)='array' and jsonb_array_length(target_response_value)>0 and not exists(select 1 from jsonb_array_elements_text(target_response_value) v where not exists(select 1 from jsonb_array_elements(q.options_snapshot) o where o->>'value'=v)) else false end;if not valid then raise exception 'invalid question response' using errcode='22023';end if;insert into public.case_question_responses(organization_id,case_id,case_question_id,response_value,responded_by_user_id) values(q.organization_id,q.case_id,q.id,target_response_value,actor) on conflict(case_question_id) do update set response_value=excluded.response_value,responded_by_user_id=actor returning * into r;insert into public.case_activity(organization_id,case_id,actor_user_id,event_type,event_data) values(q.organization_id,q.case_id,actor,'QUESTION_RESPONSE_UPDATED',jsonb_build_object('case_question_id',q.id));return r;end $$;

alter table public.case_activity drop constraint case_activity_event_type_check;alter table public.case_activity add constraint case_activity_event_type_check check(event_type in ('CASE_CREATED','CASE_ASSIGNED','CASE_UNASSIGNED','STATUS_CHANGED','PRIORITY_CHANGED','DUE_DATE_CHANGED','TASK_CREATED','TASK_UPDATED','TASK_DELETED','TASK_ASSIGNED','TASK_STARTED','TASK_COMPLETED','CUSTOMER_RESPONSE_RECEIVED','CASE_MOVED_TO_REVIEW','CASE_COMPLETED','CASE_REOPENED','QUESTION_RESPONSE_UPDATED'));
create or replace function public.guard_case_completion() returns trigger language plpgsql security definer set search_path='' as $$ begin if new.status='COMPLETED' and old.status<>'COMPLETED' and exists(select 1 from public.case_tasks t where t.case_id=new.id and t.required and t.status not in ('COMPLETED','NOT_APPLICABLE')) then raise exception 'All required applicable tasks must be completed before completing the case.' using errcode='23514';end if;if new.status='COMPLETED' and old.status<>'COMPLETED' and exists(select 1 from public.case_questions q where q.case_id=new.id and q.required and not exists(select 1 from public.case_question_responses r where r.case_question_id=q.id)) then raise exception 'All required applicable questions must be answered before completing the case.' using errcode='23514';end if;if new.status='COMPLETED' and old.status<>'COMPLETED' then new.completed_at=coalesce(new.completed_at,now());end if;if old.status='COMPLETED' and new.status in ('NEW','UNASSIGNED','ASSIGNED','IN_PROGRESS','WAITING','REVIEW') then new.completed_at=null;end if;if new.status='CLOSED' and old.status<>'CLOSED' then new.closed_at=coalesce(new.closed_at,now());end if;if old.status='CLOSED' and new.status<>'CLOSED' then new.closed_at=null;end if;return new;end $$;

alter table public.question_definitions enable row level security;alter table public.question_options enable row level security;alter table public.case_questions enable row level security;alter table public.case_question_responses enable row level security;
create policy question_definitions_select on public.question_definitions for select to authenticated using(public.is_super_admin() or public.is_internal_member(organization_id));create policy question_options_select on public.question_options for select to authenticated using(public.is_super_admin() or public.is_internal_member(organization_id));create policy case_questions_select on public.case_questions for select to authenticated using(public.can_access_case(case_id,organization_id));create policy case_responses_select on public.case_question_responses for select to authenticated using(public.can_access_case(case_id,organization_id));
revoke insert,update,delete on public.question_definitions,public.question_options,public.case_questions,public.case_question_responses from authenticated;grant select on public.question_definitions,public.question_options,public.case_questions,public.case_question_responses to authenticated;
revoke execute on function public.can_administer_questions(uuid,uuid),public.snapshot_case_questions(),public.save_question_definition(uuid,uuid,text,text,public.question_response_type,boolean,boolean,integer,jsonb),public.save_case_question_response(uuid,jsonb) from public,anon;grant execute on function public.save_question_definition(uuid,uuid,text,text,public.question_response_type,boolean,boolean,integer,jsonb),public.save_case_question_response(uuid,jsonb) to authenticated;
