import { cookies } from "next/headers";
import type { User } from "@supabase/supabase-js";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/server";
import type { Database } from "@/types/database.generated";
import { hasTenantInternalAccess } from "./access-routing";
export const ACTIVE_ORGANIZATION_COOKIE="dm3iqcm-active-organization";
type Role=Database["public"]["Enums"]["application_role"];
export interface AuthorizedOrganization{id:string;name:string;slug:string;role:Role}
export interface AccessContext{user:User;displayName:string;isSuperAdmin:boolean;organizations:AuthorizedOrganization[];activeOrganization:AuthorizedOrganization|null;customerPortalIds:string[];provisioned:boolean;internalAccess:boolean}
export type InternalAccessContext=AccessContext&{activeOrganization:AuthorizedOrganization;internalAccess:true};
export async function getAccessContext():Promise<AccessContext|null>{if(!isSupabaseConfigured())return null;try{const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const [profile,platform,memberships,portal]=await Promise.all([supabase.from("profiles").select("display_name,first_name,last_name").eq("id",user.id).maybeSingle(),supabase.from("platform_user_roles").select("id").eq("user_id",user.id).eq("role","SUPER_ADMIN").eq("is_active",true).limit(1),supabase.from("organization_members").select("organization_id,role").eq("user_id",user.id).eq("is_active",true),supabase.from("customer_portal_users").select("customer_id").eq("user_id",user.id).eq("is_active",true)]);const isSuperAdmin=Boolean(platform.data?.length);const membershipRows=memberships.data??[];const allowedIds=membershipRows.map(row=>row.organization_id);let organizationQuery=supabase.from("organizations").select("id,name,slug").eq("status","ACTIVE").order("name");if(!isSuperAdmin)organizationQuery=organizationQuery.in("id",allowedIds.length?allowedIds:["00000000-0000-0000-0000-000000000000"]);const {data:organizationRows}=await organizationQuery;const organizations:AuthorizedOrganization[]=(organizationRows??[]).map(org=>({id:org.id,name:org.name,slug:org.slug,role:isSuperAdmin?"SUPER_ADMIN":membershipRows.find(row=>row.organization_id===org.id)?.role??"STAFF_USER"}));const selected=(await cookies()).get(ACTIVE_ORGANIZATION_COOKIE)?.value;const activeOrganization=organizations.find(org=>org.id===selected)??organizations[0]??null;const customerPortalIds=(portal.data??[]).map(row=>row.customer_id);const displayName=profile.data?.display_name||[profile.data?.first_name,profile.data?.last_name].filter(Boolean).join(" ")||user.email||"DM3iQ User";return{user,displayName,isSuperAdmin,organizations,activeOrganization,customerPortalIds,provisioned:isSuperAdmin||organizations.length>0||customerPortalIds.length>0,internalAccess:isSuperAdmin||organizations.length>0};}catch(error){console.error("Unable to resolve authenticated access context",error);return null;}}
export async function requireInternalContext():Promise<InternalAccessContext>{const context=await getAccessContext();if(!context?.user||!hasTenantInternalAccess(context))throw new Error("UNAUTHORIZED");return context as InternalAccessContext;}
